version: '3'
services:
  db:
    image: postgres:10.0
    volumes:
      - pubscience_app:/var/lib/postgresql/data
    env_file:
      - .env-dev
    logging:
     driver: none
    ports:
      - '5432:5432'
  api:
    restart: always
    build: .
    entrypoint: /entrypoint.sh
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env-dev
volumes:
  pubscience_app: