# Generated by Django 2.0 on 2018-02-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='failure_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='img_directory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='success_count',
            field=models.IntegerField(null=True),
        ),
    ]
