# Generated by Django 2.0 on 2018-02-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180218_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
    ]
