# Generated by Django 2.0 on 2018-02-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180219_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='search',
            name='slug',
        ),
    ]
