# Generated by Django 2.0 on 2018-02-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180219_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='included',
            field=models.NullBooleanField(default=None),
        ),
    ]
