# Generated by Django 2.0 on 2018-02-19 07:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('directories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
