const ACTIONS = {
  FETCH_SEARCHES: 'FETCH_SEARCHES',
  CREATE_SEARCH: 'CREATE_SEARCH',
  DELETE_SEARCH: 'DELETE_SEARCH',

  TOGGLE_IMAGE_INCLUDES: 'TOGGLE_IMAGE_INCLUDES',
};

export default ACTIONS;
